name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Website to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build the libraries
        run: pnpm run --filter=@comfortdelgro/wc-compass build

      - name: Build the website
        run: pnpm run --filter=@comfortdelgro/wc-compass-website build

      - name: Export the website
        run: BASE_PATH="/wc-compass" pnpm run --filter=@comfortdelgro/wc-compass-website export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/docs/out
