name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Website to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: pnpm i

      - name: Build website
        run: pnpm run build

      - name: Start server
        run: pnpm run dev
