name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: |
          pnpm run --filter=@comfortdelgro/wc-compass build

      - name: Publish
        run: pnpm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CDG_PUBLISHER_NPM_TOKEN }}
          NPM_CONFIG_REGISTRY: 'https://registry.npmjs.org/'

      - name: Create Release Pull Request
        uses: peter-evans/create-pull-request@v3.9.2
        with:
          commit-message: 'chore: release'
          title: 'A New Release'
          body: 'This PR includes the latest changes.'
          branch: 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
